/**
 * Assessment completion component with download options
 */

import { Download, FileText, RefreshCw, AlertCircle } from 'lucide-react';
import { useState } from 'react';
import { ErrorAlert } from './ErrorAlert';

interface AssessmentCompleteProps {
  report: string;
  onStartNew: () => void;
}

export function AssessmentComplete({ report, onStartNew }: AssessmentCompleteProps) {
  const [pdfError, setPdfError] = useState('');
  const [pdfLoading, setPdfLoading] = useState(false);

  /**
   * Downloads the report as a Markdown file
   */
  const downloadMarkdown = () => {
    try {
      const blob = new Blob([report], { type: 'text/markdown' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `AI-Assessment-${new Date().toISOString().split('T')[0]}.md`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    } catch (error) {
      console.error('Error downloading Markdown:', error);
      setPdfError('Failed to download Markdown file. Please try again.');
    }
  };

  /**
   * Downloads the report as a simple HTML file (fallback for PDF)
   */
  const downloadHTML = () => {
    try {
      // Convert markdown to simple HTML
      const htmlContent = `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AI Readiness Assessment Report</title>
    <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; max-width: 800px; margin: 0 auto; padding: 20px; }
        h1, h2, h3, h4 { color: #1e40af; }
        h1 { border-bottom: 2px solid #1e40af; padding-bottom: 10px; }
        h2 { border-bottom: 1px solid #ddd; padding-bottom: 5px; }
        ul, ol { padding-left: 20px; }
        strong { color: #1e3a8a; }
        .header { text-align: center; margin-bottom: 30px; }
        .footer { margin-top: 30px; padding-top: 20px; border-top: 1px solid #ddd; font-size: 0.9em; color: #666; }
        @media print { body { margin: 0; } }
    </style>
</head>
<body>
    <div class="header">
        <h1>AI Readiness Assessment Report</h1>
        <p>Generated on ${new Date().toLocaleDateString()}</p>
    </div>
    <div class="content">
        ${convertMarkdownToHTML(report)}
    </div>
    <div class="footer">
        <p>This report was generated by the DOST-ASTI AI Readiness Assessment Tool.</p>
    </div>
</body>
</html>`;

      const blob = new Blob([htmlContent], { type: 'text/html' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `AI-Assessment-${new Date().toISOString().split('T')[0]}.html`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    } catch (error) {
      console.error('Error downloading HTML:', error);
      setPdfError('Failed to download HTML file. Please try again.');
    }
  };

  /**
   * Simple markdown to HTML converter
   */
  const convertMarkdownToHTML = (markdown: string): string => {
    return markdown
      .replace(/^# (.*$)/gim, '<h1>$1</h1>')
      .replace(/^## (.*$)/gim, '<h2>$1</h2>')
      .replace(/^### (.*$)/gim, '<h3>$1</h3>')
      .replace(/^#### (.*$)/gim, '<h4>$1</h4>')
      .replace(/\*\*(.*?)\*\*/gim, '<strong>$1</strong>')
      .replace(/\*(.*?)\*/gim, '<em>$1</em>')
      .replace(/^\* (.*$)/gim, '<li>$1</li>')
      .replace(/^\d+\. (.*$)/gim, '<li>$1</li>')
      .replace(/(<li>.*<\/li>)/s, '<ul>$1</ul>')
      .replace(/\n\n/gim, '</p><p>')
      .replace(/^(?!<[h|u|l])/gim, '<p>')
      .replace(/(?<![>])$/gim, '</p>')
      .replace(/<p><\/p>/gim, '')
      .replace(/<p>(<[h|u])/gim, '$1')
      .replace(/(<\/[h|u|l][^>]*>)<\/p>/gim, '$1');
  };

  /**
   * Generates and downloads the report as a PDF (simplified approach)
   */
  const downloadPDF = async () => {
    setPdfLoading(true);
    setPdfError('');

    try {
      // Validate report content
      if (!report || report.trim().length === 0) {
        throw new Error('Report content is empty');
      }

      // Try to use the browser's print-to-PDF functionality
      const printWindow = window.open('', '_blank');
      if (!printWindow) {
        throw new Error('Popup blocked. Please allow popups and try again.');
      }

      const htmlContent = `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AI Readiness Assessment Report</title>
    <style>
        @media print {
            body { margin: 0; font-size: 12pt; }
            .no-print { display: none; }
        }
        body { 
            font-family: Arial, sans-serif; 
            line-height: 1.6; 
            max-width: 800px; 
            margin: 0 auto; 
            padding: 20px; 
        }
        h1, h2, h3, h4 { color: #1e40af; page-break-after: avoid; }
        h1 { border-bottom: 2px solid #1e40af; padding-bottom: 10px; }
        h2 { border-bottom: 1px solid #ddd; padding-bottom: 5px; }
        ul, ol { padding-left: 20px; }
        strong { color: #1e3a8a; }
        .header { text-align: center; margin-bottom: 30px; }
        .footer { margin-top: 30px; padding-top: 20px; border-top: 1px solid #ddd; font-size: 0.9em; color: #666; }
        .print-button { 
            background: #1e40af; 
            color: white; 
            padding: 10px 20px; 
            border: none; 
            border-radius: 5px; 
            cursor: pointer; 
            margin: 20px 0; 
        }
        .print-button:hover { background: #1e3a8a; }
    </style>
</head>
<body>
    <div class="no-print">
        <button class="print-button" onclick="window.print()">Print to PDF</button>
        <p><em>Use your browser's print function and select "Save as PDF" as the destination.</em></p>
    </div>
    <div class="header">
        <h1>AI Readiness Assessment Report</h1>
        <p>Generated on ${new Date().toLocaleDateString()}</p>
    </div>
    <div class="content">
        ${convertMarkdownToHTML(report)}
    </div>
    <div class="footer">
        <p>This report was generated by the DOST-ASTI AI Readiness Assessment Tool.</p>
    </div>
</body>
</html>`;

      printWindow.document.write(htmlContent);
      printWindow.document.close();
      printWindow.focus();

      // Auto-trigger print dialog after a short delay
      setTimeout(() => {
        printWindow.print();
      }, 500);

    } catch (error) {
      console.error('Error generating PDF:', error);
      let errorMessage = 'Failed to generate PDF. ';
      
      if (error instanceof Error) {
        if (error.message.includes('Popup blocked')) {
          errorMessage += 'Please allow popups for this site and try again, or use the HTML download option.';
        } else if (error.message.includes('empty')) {
          errorMessage += 'The report content is invalid.';
        } else {
          errorMessage += error.message;
        }
      }
      
      errorMessage += ' You can download the HTML version instead, which can be printed to PDF from your browser.';
      setPdfError(errorMessage);
    } finally {
      setPdfLoading(false);
    }
  };

  return (
    <div className="space-y-4" role="region" aria-label="Assessment complete">
      {pdfError && (
        <ErrorAlert 
          message={pdfError} 
          severity="warning"
          onClose={() => setPdfError('')} 
        />
      )}

      <div className="p-6 bg-green-50 border-2 border-green-300 rounded-xl text-center">
        <h2 className="text-xl font-bold text-green-800 mb-2">Assessment Complete!</h2>
        <p className="text-gray-700 mb-4">
          Your AI readiness assessment has been completed and saved. Download your report below.
        </p>
        
        <div className="flex justify-center gap-3 flex-wrap mb-4">
          <button
            onClick={downloadMarkdown}
            className="bg-green-600 text-white px-6 py-3 rounded-xl hover:bg-green-700 transition flex items-center gap-2 font-medium shadow-sm"
            aria-label="Download assessment report as Markdown file"
          >
            <Download size={20} aria-hidden="true" />
            Download MD
          </button>
          
          <button
            onClick={downloadHTML}
            className="bg-blue-600 text-white px-6 py-3 rounded-xl hover:bg-blue-700 transition flex items-center gap-2 font-medium shadow-sm"
            aria-label="Download assessment report as HTML file"
          >
            <FileText size={20} aria-hidden="true" />
            Download HTML
          </button>
          
          <button
            onClick={downloadPDF}
            disabled={pdfLoading}
            className="bg-purple-600 text-white px-6 py-3 rounded-xl hover:bg-purple-700 transition flex items-center gap-2 font-medium shadow-sm disabled:opacity-50 disabled:cursor-not-allowed"
            aria-label="Generate PDF version (opens print dialog)"
          >
            {pdfLoading ? (
              <>
                <div className="animate-spin rounded-full h-5 w-5 border-b-2 border-white"></div>
                Generating...
              </>
            ) : (
              <>
                <FileText size={20} aria-hidden="true" />
                Print to PDF
              </>
            )}
          </button>
        </div>

        <div className="text-sm text-gray-600 mb-4 p-3 bg-blue-50 rounded-lg">
          <div className="flex items-start gap-2">
            <AlertCircle size={16} className="text-blue-600 mt-0.5 flex-shrink-0" />
            <div className="text-left">
              <p className="font-medium text-blue-800">Download Options:</p>
              <ul className="mt-1 space-y-1 text-blue-700">
                <li>• <strong>Markdown:</strong> Plain text format, works everywhere</li>
                <li>• <strong>HTML:</strong> Formatted version, can be printed to PDF</li>
                <li>• <strong>Print to PDF:</strong> Opens browser print dialog for direct PDF creation</li>
              </ul>
            </div>
          </div>
        </div>

        <button
          onClick={onStartNew}
          className="bg-gray-600 text-white px-6 py-3 rounded-xl hover:bg-gray-700 transition flex items-center gap-2 font-medium shadow-sm mx-auto"
          aria-label="Start a new assessment"
        >
          <RefreshCw size={20} aria-hidden="true" />
          Start New Assessment
        </button>
      </div>
    </div>
  );
}
