/**
 * Assessment completion component with report preview
 */

import { FileText, RefreshCw } from 'lucide-react';
import { useState } from 'react';
import { ErrorAlert } from './ErrorAlert';

interface AssessmentCompleteProps {
  report: string;
  onStartNew: () => void;
}

export function AssessmentComplete({ report, onStartNew }: AssessmentCompleteProps) {
  const [previewError, setPreviewError] = useState('');

  /**
   * Simple markdown to HTML converter
   */
  const convertMarkdownToHTML = (markdown: string): string => {
    let html = markdown
      .replace(/^# (.*$)/gim, '<h1>$1</h1>')
      .replace(/^## (.*$)/gim, '<h2>$1</h2>')
      .replace(/^### (.*$)/gim, '<h3>$1</h3>')
      .replace(/^#### (.*$)/gim, '<h4>$1</h4>')
      .replace(/\*\*(.*?)\*\*/gim, '<strong>$1</strong>')
      .replace(/\*(.*?)\*/gim, '<em>$1</em>')
      .replace(/^\* (.*$)/gim, '<li>$1</li>')
      .replace(/^\d+\. (.*$)/gim, '<li>$1</li>')
      .replace(/\n\n/gim, '</p><p>');

    html = html.replace(/(<li>.*?<\/li>(\n<li>.*?<\/li>)*)/g, '<ul>$1</ul>');

    html = html.split('\n').map(line => {
      if (line.trim() === '') return '';
      if (line.match(/^<[h1-6]|^<ul|^<\/ul/)) return line;
      if (line.match(/^<li/)) return line;
      return line.startsWith('<') ? line : `<p>${line}</p>`;
    }).join('\n');

    html = html
      .replace(/<p><\/p>/g, '')
      .replace(/<p>(<[h1-6])/g, '$1')
      .replace(/(<\/[h1-6][^>]*>)<\/p>/g, '$1')
      .replace(/<p>(<ul)/g, '$1')
      .replace(/(<\/ul>)<\/p>/g, '$1');

    return html;
  };

  /**
   * Opens a styled HTML report preview with a Print to PDF button
   */
  const viewReport = (): void => {
    setPreviewError('');

    try {
      if (!report || report.trim().length === 0) {
        setPreviewError('The report content is invalid.');
        return;
      }

      const htmlContent = `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AI Readiness Assessment Report</title>
    <style>
        @media print {
            body { margin: 0; font-size: 12pt; }
            .no-print { display: none !important; }
        }
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
        }
        h1, h2, h3, h4 { color: #1e40af; page-break-after: avoid; }
        h1 { border-bottom: 2px solid #1e40af; padding-bottom: 10px; }
        h2 { border-bottom: 1px solid #ddd; padding-bottom: 5px; }
        ul, ol { padding-left: 20px; }
        strong { color: #1e3a8a; }
        .header { text-align: center; margin-bottom: 30px; }
        .content { margin-bottom: 30px; }
        .footer { margin-top: 30px; padding-top: 20px; border-top: 1px solid #ddd; font-size: 0.9em; color: #666; }
        .toolbar {
            background: #f8fafc;
            border-bottom: 1px solid #e2e8f0;
            padding: 12px 20px;
            margin: -20px -20px 20px -20px;
            display: flex;
            align-items: center;
            gap: 12px;
        }
        .print-btn {
            background: #7c3aed;
            color: white;
            padding: 8px 20px;
            border: none;
            border-radius: 6px;
            cursor: pointer;
            font-size: 14px;
            font-weight: 500;
        }
        .print-btn:hover { background: #6d28d9; }
        .print-hint { color: #64748b; font-size: 13px; }
    </style>
</head>
<body>
    <div class="no-print toolbar">
        <button class="print-btn" onclick="window.print()">Print to PDF</button>
        <span class="print-hint">Select "Save as PDF" as the printer destination</span>
    </div>
    <div class="header">
        <h1>AI Readiness Assessment Report</h1>
        <p>Generated on ${new Date().toLocaleDateString()}</p>
    </div>
    <div class="content">
        ${convertMarkdownToHTML(report)}
    </div>
    <div class="footer">
        <p>This report was generated by the DOST-ASTI AI Readiness Assessment Tool.</p>
    </div>
</body>
</html>`;

      const previewWindow = window.open('', '_blank');
      if (!previewWindow) {
        setPreviewError('Popup blocked. Please allow popups for this site and try again.');
        return;
      }

      previewWindow.document.write(htmlContent);
      previewWindow.document.close();
      previewWindow.focus();
    } catch {
      setPreviewError('Failed to open report preview. Please try again.');
    }
  };

  return (
    <div className="space-y-4" role="region" aria-label="Assessment complete">
      {previewError && (
        <ErrorAlert
          message={previewError}
          severity="warning"
          onClose={() => setPreviewError('')}
        />
      )}

      <div className="p-6 bg-green-50 border-2 border-green-300 rounded-xl text-center">
        <h2 className="text-xl font-bold text-green-800 mb-2">Assessment Complete!</h2>
        <p className="text-gray-700 mb-4">
          Your AI readiness assessment has been completed. Preview or save your report below.
        </p>

        <div className="flex justify-center gap-3 flex-wrap mb-4">
          <button
            onClick={viewReport}
            className="bg-blue-600 text-white px-6 py-3 rounded-xl hover:bg-blue-700 transition flex items-center gap-2 font-medium shadow-sm"
            aria-label="View assessment report in new tab with option to print as PDF"
          >
            <FileText size={20} aria-hidden="true" />
            View Report
          </button>
        </div>

        <div className="text-sm text-gray-600 mb-4 p-3 bg-blue-50 rounded-lg">
          <p className="text-blue-700">
            Opens your report in a new tab. Use the <strong>Print to PDF</strong> button there to save as PDF.
          </p>
        </div>

        <button
          onClick={onStartNew}
          className="bg-gray-600 text-white px-6 py-3 rounded-xl hover:bg-gray-700 transition flex items-center gap-2 font-medium shadow-sm mx-auto"
          aria-label="Start a new assessment"
        >
          <RefreshCw size={20} aria-hidden="true" />
          Start New Assessment
        </button>
      </div>
    </div>
  );
}
